# Generated by Django 4.1.3 on 2023-04-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CanalAcupuntura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cvecanal", models.CharField(db_column="CveCanal", max_length=20)),
                ("nomcanal", models.CharField(db_column="NomCanal", max_length=80)),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
            ],
            options={
                "db_table": "CANAL_ACUPUNTURA",
            },
        ),
        migrations.CreateModel(
            name="Enfermedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cveenfermedad",
                    models.CharField(db_column="CveEnfermedad", max_length=20),
                ),
                (
                    "nomenfermedad",
                    models.CharField(db_column="NomEnfermedad", max_length=255),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
            ],
            options={
                "db_table": "ENFERMEDAD",
            },
        ),
        migrations.CreateModel(
            name="OrganoParteCuerpo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomorgpartecuerpo",
                    models.CharField(db_column="NomOrgparteCuerpo", max_length=255),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
            ],
            options={
                "db_table": "ORGANO_PARTE_CUERPO",
            },
        ),
        migrations.CreateModel(
            name="PuntoAcupuntura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cvepunto", models.CharField(db_column="CvePunto", max_length=20)),
                ("nompunto", models.CharField(db_column="NomPunto", max_length=80)),
                (
                    "nomlargopunto",
                    models.CharField(db_column="NomLargoPunto", max_length=300),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvecanal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.canalacupuntura",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_ACUPUNTURA",
            },
        ),
        migrations.CreateModel(
            name="Sintoma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sintoma", models.CharField(db_column="Sintoma", max_length=255)),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
            ],
            options={
                "db_table": "SINTOMA",
            },
        ),
        migrations.CreateModel(
            name="Sintomatologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
                (
                    "nomorgpartecuerpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.organopartecuerpo",
                    ),
                ),
                (
                    "sintoma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.sintoma",
                    ),
                ),
            ],
            options={
                "db_table": "SINTOMATOLOGIA",
            },
        ),
        migrations.CreateModel(
            name="PuntoVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ligavideo", models.CharField(db_column="LigaVideo", max_length=255)),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_VIDEOS",
            },
        ),
        migrations.CreateModel(
            name="PuntoSintomatologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
                (
                    "nomorgpartecuerpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.organopartecuerpo",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_SINTOMATOLOGIA",
            },
        ),
        migrations.CreateModel(
            name="PuntoSignificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descsignificado", models.TextField(db_column="DescSignificado")),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_SIGNIFICADO",
            },
        ),
        migrations.CreateModel(
            name="PuntoLocalizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desclocalizacion", models.TextField(db_column="DescLocalizacion")),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_LOCALIZACION",
            },
        ),
        migrations.CreateModel(
            name="PuntoImagenLocalizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ligaimagen",
                    models.CharField(db_column="LigaImagen", max_length=255),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_IMAGEN_LOCALIZACION",
            },
        ),
        migrations.CreateModel(
            name="PuntoImagenes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ligaimagen",
                    models.CharField(db_column="LigaImagen", max_length=255),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_IMAGENES",
            },
        ),
        migrations.CreateModel(
            name="PuntoEnfermedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cveenfermedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.enfermedad",
                    ),
                ),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_ENFERMEDAD",
            },
        ),
        migrations.CreateModel(
            name="PuntoDocumentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ligadocumento",
                    models.CharField(db_column="LigaDocumento", max_length=255),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_DOCUMENTOS",
            },
        ),
        migrations.CreateModel(
            name="PuntoCaracteristicas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desccaracteristicas",
                    models.TextField(db_column="DescCaracteristicas"),
                ),
                (
                    "bandactivo",
                    models.IntegerField(blank=True, db_column="BandActivo", null=True),
                ),
                ("datelastupdate", models.DateTimeField(db_column="DateLastUpdate")),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
            options={
                "db_table": "PUNTO_CARACTERISTICAS",
            },
        ),
        migrations.AddField(
            model_name="organopartecuerpo",
            name="sintoma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="puntos.sintoma"
            ),
        ),
    ]
