# Generated by Django 4.1.3 on 2023-04-14 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("puntos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canalacupuntura",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="enfermedad",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="organopartecuerpo",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntoacupuntura",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntocaracteristicas",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntodocumentos",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntoenfermedad",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntoimagenes",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntoimagenlocalizacion",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntolocalizacion",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntosignificado",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntosintomatologia",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="puntovideos",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="sintoma",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="sintomatologia",
            name="datelastupdate",
            field=models.DateTimeField(
                db_column="DateLastUpdate", default=django.utils.timezone.now
            ),
        ),
    ]
