# Generated by Django 4.1.3 on 2024-02-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enfermedad",
            name="cveenfermedad",
            field=models.CharField(
                db_column="CveEnfermedad", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="enfermedad",
            name="nomenfermedad",
            field=models.CharField(
                blank=True,
                db_column="NomEnfermedad",
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
