# Generated by Django 4.1.3 on 2023-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntos", "0002_alter_canalacupuntura_datelastupdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canalacupuntura",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="enfermedad",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="organopartecuerpo",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntoacupuntura",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntocaracteristicas",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntodocumentos",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntoenfermedad",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntoimagenes",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntoimagenlocalizacion",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntolocalizacion",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntosignificado",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntosintomatologia",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="puntovideos",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="sintoma",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
        migrations.AlterField(
            model_name="sintomatologia",
            name="bandactivo",
            field=models.BooleanField(db_column="BandActivo", default=True),
        ),
    ]
