# Generated by Django 4.1.3 on 2023-04-14 21:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puntos", "0003_alter_canalacupuntura_bandactivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puntocaracteristicas",
            name="desccaracteristicas",
            field=ckeditor.fields.RichTextField(db_column="DescCaracteristicas"),
        ),
    ]
