# Generated by Django 4.1.3 on 2023-04-23 21:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puntos", "0004_alter_puntocaracteristicas_desccaracteristicas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puntosignificado",
            name="descsignificado",
            field=ckeditor.fields.RichTextField(db_column="DescSignificado"),
        ),
    ]
