# Generated by Django 4.1.3 on 2023-05-03 19:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntos", "0005_alter_puntosignificado_descsignificado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puntocaracteristicas",
            name="desccaracteristicas",
            field=ckeditor.fields.RichTextField(
                db_column="DescCaracteristicas", verbose_name="Caracteristicas"
            ),
        ),
        migrations.AlterField(
            model_name="puntodocumentos",
            name="ligadocumento",
            field=models.CharField(
                db_column="LigaDocumento", max_length=255, verbose_name="Documento"
            ),
        ),
        migrations.AlterField(
            model_name="puntolocalizacion",
            name="desclocalizacion",
            field=models.TextField(
                db_column="DescLocalizacion", verbose_name="Localizacion"
            ),
        ),
        migrations.AlterField(
            model_name="puntosignificado",
            name="descsignificado",
            field=ckeditor.fields.RichTextField(
                db_column="DescSignificado", verbose_name="Significado"
            ),
        ),
    ]
