# Generated by Django 4.1.3 on 2023-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntos", "0007_alter_puntoimagenes_ligaimagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puntodocumentos",
            name="ligadocumento",
            field=models.FileField(
                db_column="LigaDocumento",
                max_length=255,
                upload_to="documentos_puntos",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="puntoimagenes",
            name="ligaimagen",
            field=models.ImageField(
                db_column="LigaImagen", max_length=255, upload_to="images_puntos"
            ),
        ),
    ]
