# Generated by Django 4.1.3 on 2023-10-17 23:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0008_alter_puntodocumentos_ligadocumento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParteCuerpo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TipoPunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipopunto", models.CharField(db_column="clave", max_length=20)),
                (
                    "descripciontipopunto",
                    models.CharField(db_column="nombre", max_length=80),
                ),
            ],
        ),
        migrations.AddField(
            model_name="canalacupuntura",
            name="nomchino",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="canalacupuntura",
            name="numtotalpuntos",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="canalacupuntura",
            name="traduccion",
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name="canalacupuntura",
            name="trayecto",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name="puntocaracteristicas",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.puntoacupuntura"
            ),
        ),
        migrations.AlterField(
            model_name="puntodocumentos",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.puntoacupuntura"
            ),
        ),
        migrations.AlterField(
            model_name="puntoenfermedad",
            name="cveenfermedad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.enfermedad"
            ),
        ),
        migrations.AlterField(
            model_name="puntoenfermedad",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.puntoacupuntura"
            ),
        ),
        migrations.AlterField(
            model_name="puntoimagenes",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.puntoacupuntura"
            ),
        ),
        migrations.AlterField(
            model_name="puntoimagenlocalizacion",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.puntoacupuntura"
            ),
        ),
        migrations.AlterField(
            model_name="puntolocalizacion",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.puntoacupuntura"
            ),
        ),
        migrations.AlterField(
            model_name="puntolocalizacion",
            name="desclocalizacion",
            field=ckeditor.fields.RichTextField(
                db_column="DescLocalizacion", verbose_name="Localizacion"
            ),
        ),
        migrations.AlterField(
            model_name="puntosignificado",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.puntoacupuntura"
            ),
        ),
        migrations.AlterField(
            model_name="puntosintomatologia",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.puntoacupuntura"
            ),
        ),
        migrations.AlterField(
            model_name="puntovideos",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.puntoacupuntura"
            ),
        ),
        migrations.CreateModel(
            name="TipoPuntoValores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valores", models.CharField(max_length=80)),
                (
                    "tipopunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puntos.tipopunto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TablaElementos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=80)),
                ("valores", models.CharField(max_length=80)),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emociones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emocion", models.CharField(max_length=80)),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puntos.puntoacupuntura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="puntoacupuntura",
            name="partecuerpo",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="puntos.partecuerpo",
            ),
        ),
        migrations.AlterField(
            model_name="puntosintomatologia",
            name="nomorgpartecuerpo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="puntos.partecuerpo"
            ),
        ),
        migrations.AlterField(
            model_name="sintomatologia",
            name="nomorgpartecuerpo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="puntos.partecuerpo"
            ),
        ),
        migrations.DeleteModel(
            name="OrganoParteCuerpo",
        ),
    ]
