# Generated by Django 4.1.3 on 2023-10-17 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0009_partecuerpo_tipopunto_canalacupuntura_nomchino_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puntoacupuntura",
            name="partecuerpo",
        ),
        migrations.AlterModelTable(
            name="partecuerpo",
            table="PARTE_CUERPO",
        ),
    ]
