# Generated by Django 4.1.3 on 2023-12-05 22:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0010_remove_puntoacupuntura_partecuerpo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "parte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puntos.partecuerpo",
                    ),
                ),
                (
                    "tipo_punto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puntos.tipopunto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PuntoEmocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puntos.puntoacupuntura",
                    ),
                ),
                (
                    "emocion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="puntos.emocion"
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="TablaElementos",
            new_name="Elementos",
        ),
        migrations.RemoveField(
            model_name="tipopuntovalores",
            name="tipopunto",
        ),
        migrations.AlterField(
            model_name="puntocaracteristicas",
            name="desccaracteristicas",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="DescCaracteristicas",
                verbose_name="Caracteristicas",
            ),
        ),
        migrations.AlterField(
            model_name="puntodocumentos",
            name="ligadocumento",
            field=models.FileField(
                blank=True,
                db_column="LigaDocumento",
                max_length=255,
                upload_to="documentos_puntos",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="puntoenfermedad",
            name="cveenfermedad",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="puntos.enfermedad",
            ),
        ),
        migrations.AlterField(
            model_name="puntoimagenes",
            name="ligaimagen",
            field=models.ImageField(
                blank=True,
                db_column="LigaImagen",
                max_length=255,
                upload_to="images_puntos",
            ),
        ),
        migrations.AlterField(
            model_name="puntoimagenlocalizacion",
            name="ligaimagen",
            field=models.CharField(blank=True, db_column="LigaImagen", max_length=255),
        ),
        migrations.AlterField(
            model_name="puntolocalizacion",
            name="desclocalizacion",
            field=ckeditor.fields.RichTextField(
                blank=True, db_column="DescLocalizacion", verbose_name="Localizacion"
            ),
        ),
        migrations.AlterField(
            model_name="puntosignificado",
            name="descsignificado",
            field=ckeditor.fields.RichTextField(
                blank=True, db_column="DescSignificado", verbose_name="Significado"
            ),
        ),
        migrations.AlterField(
            model_name="puntovideos",
            name="ligavideo",
            field=models.CharField(blank=True, db_column="LigaVideo", max_length=255),
        ),
        migrations.DeleteModel(
            name="Emociones",
        ),
        migrations.DeleteModel(
            name="TipoPuntoValores",
        ),
    ]
