# Generated by Django 4.1.3 on 2023-12-05 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "puntos",
            "0011_emocion_puntoemocion_rename_tablaelementos_elementos_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elementos",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="elementos",
            name="cvepunto",
        ),
        migrations.RemoveField(
            model_name="elementos",
            name="valores",
        ),
        migrations.AddField(
            model_name="elementos",
            name="descripcion",
            field=models.CharField(default="", max_length=240),
        ),
        migrations.AddField(
            model_name="elementos",
            name="nombre",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.CreateModel(
            name="PuntoElemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cvepunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puntos.puntoacupuntura",
                    ),
                ),
                (
                    "elemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puntos.elementos",
                    ),
                ),
            ],
        ),
    ]
