# Generated by Django 4.1.3 on 2024-02-07 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "puntos",
            "0012_remove_elementos_categoria_remove_elementos_cvepunto_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PuntoElemento",
            new_name="CanalElemento",
        ),
        migrations.RenameModel(
            old_name="PuntoEmocion",
            new_name="CanalEmocion",
        ),
        migrations.RenameField(
            model_name="emocion",
            old_name="nombre",
            new_name="descripcion",
        ),
        migrations.RenameField(
            model_name="tipopunto",
            old_name="descripciontipopunto",
            new_name="descripcion",
        ),
        migrations.RemoveField(
            model_name="emocion",
            name="parte",
        ),
        migrations.RemoveField(
            model_name="emocion",
            name="tipo_punto",
        ),
        migrations.RemoveField(
            model_name="puntoacupuntura",
            name="nomlargopunto",
        ),
        migrations.RemoveField(
            model_name="tipopunto",
            name="tipopunto",
        ),
        migrations.AddField(
            model_name="puntoacupuntura",
            name="nomchino",
            field=models.CharField(
                db_column="NomChino", default="chino", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="canalelemento",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.canalacupuntura"
            ),
        ),
        migrations.AlterField(
            model_name="canalemocion",
            name="cvepunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puntos.canalacupuntura"
            ),
        ),
    ]
