# Generated by Django 4.1.3 on 2024-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0013_rename_puntoelemento_canalelemento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="canalelemento",
            old_name="cvepunto",
            new_name="canal",
        ),
        migrations.RenameField(
            model_name="canalemocion",
            old_name="cvepunto",
            new_name="canal",
        ),
        migrations.RemoveField(
            model_name="emocion",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="emocion",
            name="nombre",
            field=models.CharField(default="emocion", max_length=80),
        ),
    ]
