# Generated by Django 4.1.3 on 2024-02-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0014_rename_cvepunto_canalelemento_canal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puntosintomatologia",
            name="nomorgpartecuerpo",
        ),
        migrations.AddField(
            model_name="puntosintomatologia",
            name="sintoma",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="puntos.sintoma",
            ),
        ),
        migrations.AlterField(
            model_name="canalacupuntura",
            name="nomchino",
            field=models.CharField(
                blank=True, default="nombre chino", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="canalacupuntura",
            name="numtotalpuntos",
            field=models.CharField(blank=True, default="num", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="canalacupuntura",
            name="traduccion",
            field=models.CharField(
                blank=True, default="traduccion", max_length=80, null=True
            ),
        ),
        migrations.AlterField(
            model_name="canalacupuntura",
            name="trayecto",
            field=models.CharField(
                blank=True, default="Trayecto", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sintoma",
            name="sintoma",
            field=models.CharField(
                db_column="Sintoma", default="sintoma", max_length=255
            ),
        ),
    ]
