# Generated by Django 4.1.3 on 2024-02-10 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0015_remove_puntosintomatologia_nomorgpartecuerpo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaElemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ValoresElemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TablaElementoElemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.categoriaelemento",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.elementos",
                    ),
                ),
                (
                    "valor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="puntos.valoreselemento",
                    ),
                ),
            ],
        ),
    ]
