# Generated by Django 4.1.3 on 2024-02-10 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0016_categoriaelemento_valoreselemento_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TablaElementoElemento",
            new_name="TablaElemento",
        ),
    ]
