# Generated by Django 4.1.3 on 2024-02-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0017_rename_tablaelementoelemento_tablaelemento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaelemento",
            name="nombre",
            field=models.CharField(default="", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="elementos",
            name="nombre",
            field=models.CharField(default="", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="valoreselemento",
            name="nombre",
            field=models.CharField(default="", max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="tablaelemento",
            unique_together={("tipo", "categoria", "valor")},
        ),
    ]
