# Generated by Django 4.1.3 on 2024-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0018_alter_categoriaelemento_nombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaelemento",
            name="nombre",
            field=models.CharField(default="", max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="valoreselemento",
            name="nombre",
            field=models.CharField(default="", max_length=80, unique=True),
        ),
    ]
