# Generated by Django 4.1.3 on 2024-02-13 00:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puntos", "0019_alter_categoriaelemento_nombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canalacupuntura",
            name="cvecanal",
            field=models.CharField(db_column="CveCanal", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="enfermedad",
            name="cveenfermedad",
            field=models.CharField(
                db_column="CveEnfermedad", max_length=80, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="puntoacupuntura",
            name="cvepunto",
            field=models.CharField(db_column="CvePunto", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="puntocaracteristicas",
            name="desccaracteristicas",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="DescCaracteristicas",
                unique=True,
                verbose_name="Caracteristicas",
            ),
        ),
        migrations.AlterField(
            model_name="puntodocumentos",
            name="ligadocumento",
            field=models.FileField(
                blank=True,
                db_column="LigaDocumento",
                max_length=255,
                unique=True,
                upload_to="documentos_puntos",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="puntoimagenes",
            name="ligaimagen",
            field=models.ImageField(
                blank=True,
                db_column="LigaImagen",
                max_length=255,
                unique=True,
                upload_to="images_puntos",
            ),
        ),
        migrations.AlterField(
            model_name="puntoimagenlocalizacion",
            name="ligaimagen",
            field=models.CharField(
                blank=True, db_column="LigaImagen", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="puntolocalizacion",
            name="desclocalizacion",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="DescLocalizacion",
                unique=True,
                verbose_name="Localizacion",
            ),
        ),
        migrations.AlterField(
            model_name="puntosignificado",
            name="descsignificado",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="DescSignificado",
                unique=True,
                verbose_name="Significado",
            ),
        ),
        migrations.AlterField(
            model_name="puntovideos",
            name="ligavideo",
            field=models.CharField(
                blank=True, db_column="LigaVideo", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sintoma",
            name="sintoma",
            field=models.CharField(
                db_column="Sintoma", default="sintoma", max_length=255, unique=True
            ),
        ),
    ]
